Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -116,11 +116,16 @@ jobs:
 
     - name: Post Plan in PR
       run: |
-        PLAN_OUTPUT=$(cat plan.txt)
-        COMMENT_BODY="## Terraform Plan\n\n\`\`\`\n$PLAN_OUTPUT\n\`\`\`"
-        echo "Posting comment to PR #${{ github.event.pull_request.number }}"
-        curl -v -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
-        -H "Content-Type: application/json" \
-        -X POST \
-        -d "{\"body\": \"$COMMENT_BODY\"}" \
-        "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
+        if [ -f "plan.txt" ]; then
+          PLAN_OUTPUT=$(cat plan.txt)
+          COMMENT_BODY="## Terraform Plan\n\n\`\`\`\n$PLAN_OUTPUT\n\`\`\`"
+          echo "Posting comment to PR #${{ github.event.pull_request.number }}"
+          curl -v -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          -X POST \
+          -d "{\"body\": \"$COMMENT_BODY\"}" \
+          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
+        else
+          echo "Error: plan.txt not found!"
+          exit 1
+        fi
